In [1]:
!pip install implicit


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: C:\Users\dimaz\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
!pip install h5py


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: C:\Users\dimaz\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import configparser
import os
import numpy as np
from scipy.sparse import csr_matrix
import pandas as pd
import sqlalchemy
import pickle

In [10]:
conn = sqlalchemy.create_engine("mysql+pymysql://root:Guo159753@localhost/diplom")

users_items = pd.read_sql_query("""
    with cleaned_products as (
    select id, name as product_name
    from products as p
    where is_demo_data = 0 and deleted_at is null
    ),
    cleaned_customers as (
    select id, CONCAT_WS(' ', first_name, last_name) as customer_name 
    from customers
    where is_demo_data = 0 and deleted_at is null
    )
    select distinct c.id as customer_id, customer_name, p.id as product_id, product_name, sum(bp.quantity) as quantity
    from
        cleaned_customers c
    join
        baskets b ON c.id = b.for_user
    join 
        basket_product bp on bp.basket_id = b.id
    join
        product_options po on bp.option_id = po.id
    join 
        cleaned_products p on p.id = po.product_id
    group by c.id, customer_name, p.id, product_name""", conn)

debug_names = ['DOGS', 'productimagestest', '8', 'sponge', 'First product with 1 image $100 - $80 - $20',
               'Test Price', 'NEW PRODUCT', 'cat', 'Test PP Item', 'animal shampoo', 'Product name',
               'Product placeholder', 'cap', 'new product for testing', 'ttt', 'A PRODUCT NAME', 'B PRODUCT NAME',
               'hudi 3', 'car 1', 'car 2', 'new product', 'My best product 1', 'My best product 2',
               'My best product 3',
               'My best product 4', 'My best product 5', 'Removable !!!!! product',
               'new product1', 'hudi', 'hudi 2', 'Test product', 'new product 33!', 'new product new new',
               'whatasoft.shop2222', 'Super product', 'Iphone', '123', 'sadasdasdas', 'asdasdas', 'test', 'nan',
               'test1',
               'test2', 'shop', 'a', 'test123', 'dsd', 'Product 1', 'sadsad',
               '1234', 'sdfsdfsdfsdfsdf', '3454frfdfgdfg',
               'Product with a lot of data', 'Product with SKU and no other data',
               'Product with options; not visible',
               'test 123test 123test 123test 123test 123test 123test 123test 123test 123test 123test 123test 123test 123test 123test 123test 123test 123',
               'the name', 'Product with no options', 'sort', 'Вася', 'asdasdasd',
               'sdhjsahdas', 'рарврыоа', 'qwqw', 'sadasdas',
               'Product with a bunch of test',
               'aaa 333333333 "33" <aka> \'22\' \\\\// \'Yo & Co\'',
               'empty product', 'dasda', 'Product with price',
               'Product with no stock', 'AirFort - Tiki Hut',
               "AirFort - Farmer's Barn", 'AirFort - UFO', '1', '2', 'Search 2',
               'Search123', 'New product', 'asasdas', 'New product with image',
               'New product "man suit"', 'New product 1', 'Removable product',
               'Ordered product', 'second product with images', 'New product233',
               'Search', 'Iphone 2', 'Iphone 3', 'Iphone 1', 'v', 'Test',
               'Iphone1', 'Product 22', 'Product 23', '0', 'Empty',
               'whatasoft.shop', 'TTMZ', 'd', 'whatasoft.shop update']

users_items = users_items[~users_items['product_name'].isin(debug_names)]
customer_id = users_items['customer_id'].unique()
product_id = users_items['product_id'].unique()

customers = users_items[['customer_id', 'customer_name']].drop_duplicates(subset='customer_id').reset_index(drop=True)
products = users_items[['product_id', 'product_name']].drop_duplicates(subset='product_id').reset_index(drop=True)

users_items_matrix = np.zeros(shape=(customer_id.size, product_id.size))

user_indices_to_populate = [np.where(customer_id == i)[0][0] for i in users_items['customer_id']]
item_indices_to_populate = [np.where(product_id == i)[0][0] for i in users_items['product_id']]
item_quantity = users_items['quantity'].values

for i in range(len(user_indices_to_populate)):
    users_items_matrix[user_indices_to_populate[i], item_indices_to_populate[i]] += item_quantity[i]

users_items_csr_matrix = csr_matrix(users_items_matrix)

In [ ]:
from implicit.nearest_neighbours import CosineRecommender
model = CosineRecommender(K=10)

model.fit(users_items_csr_matrix)

In [5]:
def get_model_id_by_db_id(database_id):
        return products.index[products['product_id'] == database_id].tolist()[0]

def get_db_id_by_model_id(model_id):
    return products.iloc[model_id]['product_id']

vectorized_get_db_id_by_model_id = np.vectorize(get_db_id_by_model_id)

def get_product_name_by_db_id(database_id):
    return products.loc[products['product_id'] == database_id].product_name.values[0]

vectorized_get_product_name_by_db_id = np.vectorize(get_product_name_by_db_id)

def recommend(database_id, get_scores=False, minimum_score=-1):
    model_id = get_model_id_by_db_id(database_id)
    prediction = model.similar_items(model_id, filter_items=model_id)
    recommendation_scores = prediction[1]
    elements_to_keep_count = len(recommendation_scores[recommendation_scores > minimum_score])
    recommendation_ids = vectorized_get_db_id_by_model_id(prediction[0])[:elements_to_keep_count]
    recommendation_scores = recommendation_scores[:elements_to_keep_count]
    if get_scores:
        return (recommendation_ids, recommendation_scores)
    else:
        return recommendation_ids

def recommend_product_names(database_id, get_scores=False, minimum_score=-1):
    recommendations = recommend(database_id, get_scores, minimum_score)
    if type(recommendations) is tuple:
        return (vectorized_get_product_name_by_db_id(recommendations[0]), recommendations[1])
    else:
        return vectorized_get_product_name_by_db_id(recommendations)

In [6]:
recommendations = recommend(1923)
recommendations

array([1935, 1929, 1932, 1937, 1936, 1927, 1934, 1925, 1941], dtype=int64)

In [7]:
vectorized_get_product_name_by_db_id(recommendations)

C:\Users\dimaz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\function_base.py:2455: RuntimeWarning: invalid value encountered in get_product_name_by_db_id (vectorized)
  outputs = ufunc(*inputs)


array(['The Original AirFort - Beach Ball Blue (Retail Box)',
       'The Original AirFort - Pink/White (Retail Box)',
       'The Original AirFort - Pink/White (Poly Bag)',
       'The Original AirFort - Mod About Gray (Retail Box)',
       'The Original AirFort - Digi Camo (Retail Box)',
       'The Original AirFort - Starry Night (Retail Box)',
       "The Original AirFort - Farmer's Barn (Retail Box)",
       'The Original AirFort - Mod About Gray (Poly Bag)',
       'The Original AirFort - UFO (Retail Box)'], dtype='<U51')

In [8]:
recommend_product_names(1923)

array(['The Original AirFort - Beach Ball Blue (Retail Box)',
       'The Original AirFort - Pink/White (Retail Box)',
       'The Original AirFort - Pink/White (Poly Bag)',
       'The Original AirFort - Mod About Gray (Retail Box)',
       'The Original AirFort - Digi Camo (Retail Box)',
       'The Original AirFort - Starry Night (Retail Box)',
       "The Original AirFort - Farmer's Barn (Retail Box)",
       'The Original AirFort - Mod About Gray (Poly Bag)',
       'The Original AirFort - UFO (Retail Box)'], dtype='<U51')

In [9]:
model.recommend(107, users_items_csr_matrix)

(array([17, 21, 23,  2,  8, 16, 24,  7,  9,  1]),
 array([6.4570677 , 5.88928473, 3.20504516, 0.89531376, 0.7154156 ,
        0.63048914, 0.54332393, 0.53346904, 0.53181574, 0.48071658]))

In [10]:
np.where(customer_id == 33146)

(array([107], dtype=int64),)

In [11]:
recs = model.similar_items(23, filter_items=[23])
recs

(array([24, 21, 10, 14,  4, 17, 22, 11,  6]),
 array([0.71831613, 0.7042839 , 0.68467668, 0.6531022 , 0.64755257,
        0.64087984, 0.62824309, 0.59147062, 0.57563491]))

In [12]:
sum = 0
for i in range(len(recs[1])):
    if users_items_csr_matrix.toarray()[107,:][recs[0][i]] > 0:
        sum += recs[1][i]
sum

5.191057744953332

In [13]:
for i in range(len(users_items_csr_matrix.toarray()[107,:])):
    if users_items_csr_matrix.toarray()[107,:][i] > 0:
        print(i)

3
4
6
7
10
11
12
13
15
17
21
22
23
24
25


In [14]:
sum1 = 0
sum2 = 0
for i in range(len(recs[1])):
    sum1 += (users_items_csr_matrix.toarray()[107,:][recs[0][i]]) * recs[1][i]
    sum2 += recs[1][i]
sum1 / sum2

0.8882470351985705

In [15]:
users_items[users_items['product_id'] == 2697]

customer_id  product_id       product_name
8835        39496        2697  MINI Travel Dryer

In [16]:
np.where(customer_id == 39496)

(array([1227], dtype=int64),)

In [17]:
customer_id[3]

35228

In [18]:
users_items[users_items['customer_id'] == 35228]

customer_id  product_id  \
145         35228        1923   
408         35228        1927   
1394        35228        1929   
1988        35228        1930   
2001        35228        1932   
2012        35228        1933   
2082        35228        1934   
2857        35228        1935   
3660        35228        1936   
3793        35228        1937   
4104        35228        1938   
4654        35228        1939   
5087        35228        1940   
5514        35228        1941   
6139        35228        1945   
6364        35228        1968   
6890        35228        1969   
7541        35228        2010   
8042        35228        2045   
8503        35228        2248   

                                           product_name  
145      The Original AirFort - Starry Night (Poly Bag)  
408    The Original AirFort - Starry Night (Retail Box)  
1394     The Original AirFort - Pink/White (Retail Box)  
1988  The Original AirFort - Beach Ball Blue (Poly Bag)  
2001       The Original AirFort - Pink/White (Poly Bag)  
2012       The Original AirFort - Ocean Camo (Poly Bag)  
2082  The Original AirFort - Farmer's Barn (Retail Box)  
2857  The Original AirFort - Beach Ball Blue (Retail...  
3660      The Original AirFort - Digi Camo (Retail Box)  
3793  The Original AirFort - Mod About Gray (Retail ...  
4104    The Original AirFort - Jungle Camo (Retail Box)  
4654     The Original AirFort - Ocean Camo (Retail Box)  
5087       The Original AirFort - Tiki Hut (Retail Box)  
5514            The Original AirFort - UFO (Retail Box)  
6139  The Original AirFort - Creamsicle Orange (Reta...  
6364        The Original AirFort - Cottage (Retail Box)  
6890          The Original AirFort - Cabin (Retail Box)  
7541   The Original AirFort - Royal Castle (Retail Box)  
8042  The Original AirFort - Constellation (Retail Box)  
8503  The Original AirFort - Mushroom House (Retail ...

In [19]:
vectorized_get_model_id_by_db_id = np.vectorize(get_model_id_by_db_id)

In [20]:
np.where(users_items_csr_matrix.toarray()[-1,:] > 0)

(array([52], dtype=int64),)

In [21]:
vectorized_get_product_name_by_db_id(vectorized_get_db_id_by_model_id([2, 19,  1, 18,  3, 26, 41, 51, 47, 5]))

C:\Users\dimaz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\lib\function_base.py:2455: RuntimeWarning: invalid value encountered in get_product_name_by_db_id (vectorized)
  outputs = ufunc(*inputs)


array(['The Original AirFort - Mod About Gray (Poly Bag)',
       'The Original AirFort - Digi Camo (Poly Bag)',
       'The Original AirFort - Tiki Hut (Poly Bag)',
       'The Original AirFort - Jungle Camo (Poly Bag)',
       'Product The Original AirFort - UFO (Poly Bag)',
       'Product The Original AirFort - Cottage (Poly Bag)',
       'The Original AirFort - Space Shuttle (Retail Box)',
       'MINI Travel Dryer', 'Sunday Golf Rope Hat | BLACK/WHT',
       "The Original AirFort - Farmer's Barn (Poly Bag)"], dtype='<U49')

In [22]:
np.where(customer_id == 33289)[0][0]

2

In [23]:
prods = pd.read_sql_query("select * from products", conn)
prods

id  user_id               name  sort  \
0        1        2             Iphone   0.0   
1        2        2                123   0.0   
2        3        2        sadasdasdas   0.0   
3        4        2           asdasdas   0.0   
4        5        2               test   0.0   
...    ...      ...                ...   ...   
1220  2721    44580        Gift Basket   0.0   
1221  2722    44580    Truck Bed Liner   0.0   
1222  2723    39494  Mini Travel Dryer   0.0   
1223  2724        2      Palazzo pants   0.0   
1224  2725        2                  1   NaN   

                                     description assets_url  height  width  \
0                                           None       None     5.0   10.0   
1                                           None       None     0.0    0.0   
2                                           None       None     0.0    0.0   
3                                           None       None     0.0    0.0   
4                                           None       None     0.0    0.0   
...                                          ...        ...     ...    ...   
1220  <p>\r\n\tSuper product description\r\n</p>       None     3.0    2.0   
1221  <p>\r\n\tSuper product description\r\n</p>       None     3.0    2.0   
1222                                        None       None     0.0    0.0   
1223                                        None       None     0.0    0.0   
1224                                        None       None     NaN    NaN   

      length  weight  ...          created_at          updated_at  \
0       10.0    10.0  ... 2021-04-25 16:27:01 2021-04-25 16:27:01   
1        0.0     0.0  ... 2021-03-12 09:27:08 2021-03-17 19:09:03   
2        0.0     0.0  ... 2021-03-12 09:27:08 2021-03-17 19:08:58   
3        0.0     0.0  ... 2021-03-12 09:27:08 2021-03-17 19:08:54   
4        0.0     0.0  ... 2021-03-12 09:27:08 2021-03-17 19:08:50   
...      ...     ...  ...                 ...                 ...   
1220     1.0     1.0  ... 2024-02-29 13:31:19 2024-02-29 13:31:19   
1221     1.0     1.0  ... 2024-02-29 13:31:19 2024-02-29 13:31:19   
1222     0.0     0.0  ... 2024-02-29 14:25:00 2024-02-29 14:26:03   
1223     0.0     0.0  ... 2024-03-01 04:03:24 2024-03-01 04:04:03   
1224     NaN     NaN  ... 2024-03-01 06:46:21 2024-03-01 06:46:21   

              deleted_at sales_count sales_amount is_demo_data  \
0    2021-03-17 19:09:06           0         0.00            0   
1    2021-03-17 19:09:03           0         0.00            0   
2    2021-03-17 19:08:58           0         0.00            0   
3    2021-03-17 19:08:54           0         0.00            0   
4    2021-03-17 19:08:50           0         0.00            0   
...                  ...         ...          ...          ...   
1220                 NaT          32     19080.00            1   
1221                 NaT          19     11400.00            1   
1222                 NaT           1        24.49            0   
1223                 NaT           2       183.00            0   
1224                 NaT           0         0.00            0   

      cartrover_product_id  lead_time  integration_id  source_name  
0                      NaN        0.0             NaN         None  
1                      NaN        0.0             NaN         None  
2                      NaN        0.0             NaN         None  
3                      NaN        0.0             NaN         None  
4                      NaN        0.0             NaN         None  
...                    ...        ...             ...          ...  
1220                   NaN        0.0             NaN         None  
1221                   NaN        0.0             NaN         None  
1222                   NaN        0.0             NaN         None  
1223                   NaN        0.0             NaN         None  
1224                   NaN        NaN             NaN         None  

[1225 rows x 23 columns]

In [24]:
list(prods)

['id',
 'user_id',
 'name',
 'sort',
 'description',
 'assets_url',
 'height',
 'width',
 'length',
 'weight',
 'display_type',
 'photo',
 'code',
 'created_at',
 'updated_at',
 'deleted_at',
 'sales_count',
 'sales_amount',
 'is_demo_data',
 'cartrover_product_id',
 'lead_time',
 'integration_id',
 'source_name']

In [25]:
prods_string = """'id',
 'user_id',
 'name',
 'sort',
 'description',
 'assets_url',
 'height',
 'width',
 'length',
 'weight',
 'display_type',
 'photo',
 'code',
 'created_at',
 'updated_at',
 'deleted_at',
 'sales_count',
 'sales_amount',
 'is_demo_data',
 'cartrover_product_id',
 'lead_time',
 'integration_id',
 'source_name'"""

In [29]:
prods_string_cleaned = prods_string.replace("'", "").replace("\n", "")
prods_string_cleaned

'id, user_id, name, sort, description, assets_url, height, width, length, weight, display_type, photo, code, created_at, updated_at, deleted_at, sales_count, sales_amount, is_demo_data, cartrover_product_id, lead_time, integration_id, source_name'